baseURL = 'https://hugoandcms.netlify.app'
languageCode = 'en-us'
title = 'hugoTestSite3'
theme = 'ananke'
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'